using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Carpmosia.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class EmergencyUiFragment : BoxContainer
{
    public event Action<string>? OnEmergencyMessage;

    public EmergencyUiFragment()
    {/*
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        UpdateState(new List<string>());
    */}

    public void UpdateState(List<string> notes)
    {/*
        MessageContainer.RemoveAllChildren();

        foreach (var note in notes)
        {
           AddNote(note);
        }
    */}

    private void SendMessage(string note)
    {/*
        var row = new BoxContainer();
        row.HorizontalExpand = true;
        row.Orientation = LayoutOrientation.Horizontal;
        row.Margin = new Thickness(4);

        var label = new Label();
        label.Text = note;
        label.HorizontalExpand = true;
        label.ClipText = true;

        var removeButton = new TextureButton();
        removeButton.AddStyleClass("windowCloseButton");
        removeButton.OnPressed += _ => OnNoteRemoved?.Invoke(label.Text);

        row.AddChild(label);
        row.AddChild(removeButton);

        MessageContainer.AddChild(row);
    */}
}
