using Content.Client.Message;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Shared._Carpmosia.CartridgeLoader.Cartridges;
using Robust.Shared.Utility;

namespace Content.Client._Carpmosia.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class EmergencyUiFragment : BoxContainer
{
    public event Action<string>? OnEmergencyMessage;

    public EmergencyUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;
        /*
        EmergencyUiState state = new EmergencyUiState();

        UpdateState(state);
        */
    }

    public void UpdateState(EmergencyUiState state)
    {
        DelayLabel.SetMarkup(Loc.GetString("emergency-ui-timer",
                ("time", state.NextMessage)));
        NamePreview.SetMarkup(Loc.GetString("emergency-ui-name",
                ("time", state.LastIdName)));
        LocationPreview.SetMarkup(Loc.GetString("emergency-ui-location",
                ("time", state.LastLocationName)));
    }
}
